package com.covideinfo.enums;

public enum StaticData {
	UK, US, EN, ENGLISH, MEXICO, ES, SPANISH,

	ADMISSION, PERIOD, POSTPERIOD,

	INJECTION, TABLET, FAST, FED, FASTANDFED, OPENLABEL, SINGLEBLIND, DOUBLEBLIND, SHOW, HIDE, SINGLE, MULTIPLE,
	SINGLEANDMULTIPLE, MULTY, YES, NO, PILOT, PEYOTE, MINUTES, HOURS, DAYS,
	// Dose Perameters
	TEXT, RADIO, CHECKBOX, SELECT, TEXTAREA,
//	LIGHTCONDITION
	NORMAL, MONOCHROMATIC, K2EDTA,
	// Sample Time points
	PREDOSE, POSTDOSE, AMBULATORY,
	// meals Time points
	NORMALBREAKFAST, STANDARDBREAKFAST, HIGHFATBREAKFAST, LUNCH, SNACKS, DINNER, FULL, HALF, NOTHING,
	// Vital time points
	PRONE, SUPINE, FOREHEAD, RESPIRATORYRATE, BP, WELLBEING, PULSERATE, TEMPERATURE,
//	CENTRIFUGATIONCONDITION
	ALL, VACUTAINER1, VACUTAINER2, VACUTAINER3, VACUTAINER4, VACUTAINER5, BUFFER, SERUM, PLASMA, WHOLEBLOOD, OTHERS,
	STARTTIME, ENDTIME, TIMEPOINTWISE, SUBJECTWISE,

	CONDITION1, CONDITION2, CONDITION3,
//	Restrictions Compliance Monitoring
	CHECKIN, CHECKOUT, OTHER, PLUSANDMINUS, MINUS, PLUS,

//	DeviationCodes
	CODE1, CODE2, CODE3, CODE4, CODE5, CODE6,
	
	MALE, FEMALE, BOTH,
	
	CENTRIFUGATION,DEEPFREEZER,DATALGGER
	
	
}
