package com.covideinfo.enums;

public enum StudyStatus {
	// STUDY STATUS
	STUDINFORMATION, ACTIVE, INACTIVE, DRAFT, INREVIEW, APPROVED, DESIGN, INPROGRESS, ONHOLD, ARCHIVED,
	CANCELED, SUBMIT, ACCEPT,APPROVAL,

//	Volunteer enroll Satatus
	SELECTED, ENROLLED, REPLACED, WITHDRAWN, DROPED, COMPLETED, CLOSE, OPEN,
//	Volunteer volunteer Satatus 
	// ENROLLED, WITHDRAWN ,
	DROPPED, FOR_PERIOD,
	
	//Period
	NEW,
	//Role
	ROLEINACTIVE,ROLEACTIVE,
}
