package com.covideinfo.enums;

public enum StudyDesign {
	ACTIVITY,
	LANGUAGE,
	ENGLISH,
	MEXICO,
	STUDINFORMATION,
	
	PROJECTNO,
	SPONSORCODE,
	STUDYDESIGN,
	STUDYTITLE,
	NOOFPERIODS,
	WASHOUTPERIOD,
	DOSAGEFORM,
	TREATMENTCODE,
	NOOFSUBJECTS,
	NOOFSTANDBYSUBJECTS,
	DOSETYPE,
	NOOFTREATMENTS,
	PREDOSEHR,
	POSTDOSEHR,
	TREATMENTWISEDOSEPERAMETER,
	TREATMENTSPECIFICSAMPLETIMEPOINTS,
	TREATMENTWISEMEALSTIMEPOINTS,
	TREATMENTWISEVITALTIMEPOINTS,
	TREATMENTWISEECGTIMEPOITNS,
	STUDYCATEGORY,
	
	PERIODTYPE,
	ADMISSION,
	PERIOD,
	
	TREATMENTNO,
	TREATMENTNAME,	
	FASTINGINFO,
	RANDAMIZATIONCODE,
	STREANGTH,
	DOSE,
	NOOFDOSINGS,
	AMOUNTOFWATERCONSUMEDWITHTHEDOSE,
	TREATMENTTYPE,
	NOOFSACHETLABLES,
	
	//Dose Time points
	TREATMENTWISENOOFDOSING,
	
	DOSETIMEPOINT,
	FASTINGCRITERIA,
	FASTINGCRITERIATYPE,
	FEDCRITERIA,
	FEDCRITERIATYPE,
	WINDOWPERIODSIGN,
	WINDOWPERIOD,
	WINDOWPERIODTYPE,
	
	//Dose perameters
	TREATMENT,
	PARAMETERDESC,
	CONTROLTYPE,
	
	//sample timepoints
	LIGHTCONDITION,
	BUFFER,
	VOLUMNOFBLOOD,
	TYPEOFVACUTAINERUSED,
	NOOFVAILSFORSAMPLESEPARATION,
	INTERVALBETWEENSUBJECT,
	TOTALSAMPLETIMEPOINTS,
	
	
	TIMEPOINT,
	TIMEPOINTTYPE,
	NOOFVACUTAINERS,
	NOOFVIALS,
//	WINDOWPERIODSIGN,
//	WINDOWPERIOD,
//	WINDOWPERIODTYPE,
	
	//Meals timepoints
//	TIMEPOINTTYPE,
	MEALSTTYPE,
	COMPLETIONTYPE,
	COMPLETIONTIME,
	TOTALTIMEPOINTS,
	CONSUMPTION,
	
	//Vital timepoints
	VITALPOSITION,
	TEMPERATURE,
	TESTNAMES,
	ORTHOSTATIC,
	TESTNAME,
	TESTRANGEFROM,
	TESTRANGETO,
	
	//ECG timepoitns
	ECGAPPLICABLE,
	ECGPOSITION,
	NOOFECGTIMEPOINTS,
	
//	Additional Assesment
	TITLE,
//	TIMEPOINT,
//	TIMEPOINTTYPE,
//	WINDOWPERIODSIGN,
//	WINDOWPERIOD,
//	WINDOWPERIODTYPE,
	
//	centrifugation
	CENTRIFUGATIONAPPLICABLE,
	CENTRIFUGATIONAPPLICABLEFOR,
	ALLOWEDTIME, 
	SPEED,
	PROCESSTIME,
//	TEMPERATURE,
	TEMPERATUREWINDOW,
	TEMPERATUREWINDOWSIGN,
	CENTRIFUGATIONCONDITION,
	
//	sampleProcess
	PROCESSCONDITION,
	PROCESSMATRIX,
	PROCESSALLOWEDTIME,
	PROCESSALLOWEDTIMEFROM,
	ALIQUOTS1VOLUME,
	ALIQUOTS1MATRIX,
	
//	Storage Condition
	ISSTORAGEDIFF,
	STORAGECONDITION,
	STORAGEALLOWEDTIME, 
	STORATETEMPERATURE,
	STORAGE,
	
//	Restrictions Compliance Monitoring
	RESTRICTIONSFOR,
	
//	inclustion & exclustion
	PARAMETER,
	
	
//	Samplecollection dev
	SAMPLECOLLECTIONDEVIATIONS,
	DOSEFROMCOMMENTS,
	GENDER,
	RESTRICTIONACTIVITY,
	MASKING
	
}
