package com.covideinfo.pdf.report;


import java.text.SimpleDateFormat;
import java.util.Date;

import com.covideinfo.model.UserMaster;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.ColumnText;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfPageEventHelper;
import com.itextpdf.text.pdf.PdfWriter;

public class HeaderFooterForDrugDispansingPdf extends PdfPageEventHelper {
	private String imgLoc;
	private Font regular;
	private Font mainHeading;
	private String dateStrWithTime;
	private UserMaster user;
	public HeaderFooterForDrugDispansingPdf(String imagePath, UserMaster user, Font regular, Font mainHeading, String dateStrWithTime) {
		this.imgLoc = imagePath;
		this.regular = regular;
		this.mainHeading = mainHeading;
		this.dateStrWithTime = dateStrWithTime;
		this.user = user;
	}
	@Override
	public void onStartPage(PdfWriter pdfWriter, Document document) {
		try {
			//For A4 
			Image img = Image.getInstance(imgLoc);
			img.setAbsolutePosition(40, 795); 
            img.scaleAbsolute(80, 30);
            document.add(img);
            
			//For A4 Rotation
			/*Image img2 = Image.getInstance(imgLoc);
			img2.setAbsolutePosition(200, 510); 
            img2.scaleAbsolute(100, 60);*/
			
			//Legal rotate
			/*Image img = Image.getInstance(imgLoc);
			img.setAbsolutePosition(293, 530); 
            img.scaleAbsolute(100, 60);
            document.add(img);*/
            
            
            PdfPCell cell = null;
            
            PdfPTable table2 = new PdfPTable(1);
            table2.setWidthPercentage(100f);
            
            cell= new PdfPCell(new Phrase(""));
            cell.setBorder(Rectangle.NO_BORDER);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setFixedHeight(40f);
            table2.addCell(cell);
            
            cell = new PdfPCell(new Phrase("Template Title : Investigational Product Dispensing Labels", regular));
			cell.setHorizontalAlignment(Element.ALIGN_LEFT);
			cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
			cell.setBorderColor(new BaseColor(73, 74, 82)); //##494c52
			cell.setPaddingTop(3f);
		    cell.setPaddingBottom(7f);
		    cell.setPaddingLeft(7f);
		    cell.setPaddingRight(7f);
		    cell.setNoWrap(false);
		    table2.addCell(cell);
		    
		    cell = new PdfPCell(new Phrase("SOP Ref. No.: CL-07", regular));
			cell.setHorizontalAlignment(Element.ALIGN_LEFT);
			cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
			cell.setBorderColor(new BaseColor(73, 74, 82)); //##494c52
			cell.setPaddingTop(3f);
		    cell.setPaddingBottom(7f);
		    cell.setPaddingLeft(7f);
		    cell.setPaddingRight(7f);
		    cell.setNoWrap(false);
		    table2.addCell(cell);
		    
		    document.add(table2);
       	}catch (Exception e) {
			e.printStackTrace();
		}
	}
	@Override
    public void onEndPage(PdfWriter writer, Document document) {
		try {
		    ColumnText.showTextAligned(writer.getDirectContent(), Element.ALIGN_LEFT, new Phrase("Prepared by:____________________", regular), 40, 80, 0);
			ColumnText.showTextAligned(writer.getDirectContent(), Element.ALIGN_LEFT, new Phrase("Verified by:____________________", regular), 380, 80, 0);
			
		    SimpleDateFormat sdf = new SimpleDateFormat(dateStrWithTime);
			String date = sdf.format(new Date());
			ColumnText.showTextAligned(writer.getDirectContent(), Element.ALIGN_LEFT, new Phrase("Generated By   : "+user.getFullName() + " at : "+date, regular), 40, 50, 0);
			ColumnText.showTextAligned(writer.getDirectContent(), Element.ALIGN_LEFT, new Phrase("* This document is an electronically authenticated at IST (+5:30 GMT).", regular), 40, 30, 0);
		}catch(Exception e) {
			e.printStackTrace();
		}	
    }
	
}



